#!/usr/bin/env bash
# STELE FPGA — idempotent toolchain setup for aarch64 (Radxa Q6A).
# Primary path: YosysHQ OSS CAD Suite prebuilt linux-arm64 bundle.
# Safe to re-run: skips download/extract when already installed.
set -euo pipefail

PIN_TAG="2026-07-03"
PIN_ASSET="oss-cad-suite-linux-arm64-20260703.tgz"
PIN_URL="https://github.com/YosysHQ/oss-cad-suite-build/releases/download/${PIN_TAG}/${PIN_ASSET}"
EDA_DIR="${HOME}/eda"
SUITE_DIR="${EDA_DIR}/oss-cad-suite"
PROJ_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

arch="$(uname -m)"
if [ "$arch" != "aarch64" ]; then
    echo "ERROR: expected aarch64, got $arch" >&2
    exit 1
fi

mkdir -p "$EDA_DIR"

if [ -x "${SUITE_DIR}/bin/yosys" ]; then
    echo "OSS CAD Suite already installed at ${SUITE_DIR} — skipping download."
else
    tgz="${EDA_DIR}/${PIN_ASSET}"
    if [ ! -f "$tgz" ]; then
        echo "Downloading ${PIN_URL} ..."
        curl -L --fail --retry 3 -o "${tgz}.part" "$PIN_URL"
        mv "${tgz}.part" "$tgz"
    fi
    echo "Extracting to ${EDA_DIR} ..."
    tar -xzf "$tgz" -C "$EDA_DIR"
    [ -x "${SUITE_DIR}/bin/yosys" ] || { echo "ERROR: extract did not produce ${SUITE_DIR}/bin/yosys" >&2; exit 1; }
fi

# Project env file sourced by every later stage.
cat > "${PROJ_DIR}/env.sh" <<EOF
# Auto-generated by scripts/setup_toolchain.sh — source this before any build step.
source "${SUITE_DIR}/environment"
EOF

# Python deps for the golden model go into the suite's bundled python.
source "${SUITE_DIR}/environment"
python3 -c "import numpy" 2>/dev/null || python3 -m pip install --quiet numpy

# Verification gate (runbook §3): every tool must report a version
# (icepack/icetime have no version flag — presence on PATH is the check).
echo "=== Toolchain verification gate ==="
fail=0
check() { # name, command...
    local name="$1"; shift
    if v="$("$@" 2>&1 | head -1)"; then
        echo "OK   $name: $v"
    else
        echo "FAIL $name"; fail=1
    fi
}
check yosys yosys --version
check nextpnr-ice40 nextpnr-ice40 --version
check verilator verilator --version
for tool in iverilog icepack icetime vvp; do
    if command -v "$tool" >/dev/null; then
        echo "OK   $tool: $(command -v "$tool")"
    else
        echo "FAIL $tool"; fail=1
    fi
done
if python3 -c "import cocotb, numpy; print('OK   python: cocotb', cocotb.__version__, '/ numpy', numpy.__version__)"; then
    :
else
    echo "FAIL python cocotb/numpy"; fail=1
fi
exit $fail
