"""Piecewise-linear nonlinearity tables shared between the numpy golden model
and the RTL (rtl/pwl_tables.vh is generated from this module).

All three functions use the same evaluator (mirrored bit-for-bit in
rtl/pwl_nonlin.v):

    x   = clamp(x, XMIN, XMAX)
    u   = x - XMIN
    s   = u >> SEG_SHIFT              # segment index, 0..7
    dx  = u & (SEG_SIZE - 1)
    y   = B[s] + ((M[s]*dx + (1 << (MSHIFT-1))) >> MSHIFT)   # floor shift
    y   = clamp(y, YMIN, YMAX)

Fixed-point formats (see ASSUMPTIONS.md):
    softplus : in  int8  Q4.3  (v = x/8)   -> out uint8 Q4.4 (y = f*16)
    silu     : in  int8  Q4.3  (v = x/8)   -> out int8  Q4.3 (y = f*8)
    exp      : in  int16 Q8.8, domain [-2048,-1] (v = x/256)
                                           -> out uint8 Q0.7 (y = f*128)
"""

import math

NSEG = 8


class PwlSpec:
    def __init__(self, name, xmin, xmax, seg_shift, mshift,
                 func, inscale, outscale, ymin, ymax):
        self.name = name
        self.xmin = xmin
        self.xmax = xmax              # inclusive
        self.seg_shift = seg_shift
        self.seg_size = 1 << seg_shift
        self.mshift = mshift
        self.ymin = ymin
        self.ymax = ymax
        assert (xmax - xmin + 1) == NSEG * self.seg_size
        yf = lambda xi: func(xi / inscale) * outscale
        self.B = []
        self.M = []
        for s in range(NSEG):
            x0 = xmin + s * self.seg_size
            x1 = x0 + self.seg_size
            y0 = yf(x0)
            y1 = yf(x1)
            self.B.append(int(round(y0)))
            self.M.append(int(round((y1 - y0) * (1 << mshift) / self.seg_size)))

    def eval(self, x):
        x = int(x)
        x = max(self.xmin, min(self.xmax, x))
        u = x - self.xmin
        s = u >> self.seg_shift
        dx = u & (self.seg_size - 1)
        y = self.B[s] + ((self.M[s] * dx + (1 << (self.mshift - 1))) >> self.mshift)
        return max(self.ymin, min(self.ymax, y))


def _softplus(v):
    return math.log1p(math.exp(-abs(v))) + max(v, 0.0)


def _silu(v):
    return v / (1.0 + math.exp(-v))


SOFTPLUS = PwlSpec("softplus", -128, 127, seg_shift=5, mshift=6,
                   func=_softplus, inscale=8.0, outscale=16.0,
                   ymin=0, ymax=255)

SILU = PwlSpec("silu", -128, 127, seg_shift=5, mshift=6,
               func=_silu, inscale=8.0, outscale=8.0,
               ymin=-128, ymax=127)

EXP = PwlSpec("exp", -2048, -1, seg_shift=8, mshift=8,
              func=math.exp, inscale=256.0, outscale=128.0,
              ymin=0, ymax=127)

TABLES = [SOFTPLUS, SILU, EXP]


def emit_verilog_header(path):
    """Emit rtl/pwl_tables.vh — flat packed localparams, 10-bit signed lanes,
    element 0 in the least-significant lane."""
    def flat(vals):
        bits = ""
        for v in reversed(vals):
            bits += format(v & 0x3FF, "010b")
        return f"80'b{bits}"

    lines = [
        "// AUTO-GENERATED by golden/reference_model.py from golden/pwl.py.",
        "// Do not edit. 8 segments per function, 10-bit signed lanes,",
        "// element 0 in bits [9:0].",
    ]
    for t in TABLES:
        n = t.name.upper()
        lines += [
            f"localparam [79:0] PWL_{n}_B = {flat(t.B)};",
            f"localparam [79:0] PWL_{n}_M = {flat(t.M)};",
        ]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
